revoke execute on function public.bump_post_counter() from public;
revoke execute on function public.bump_follow_counters() from public;
revoke execute on function public.bump_story_likes() from public;
revoke execute on function public.touch_conversation() from public;
revoke execute on function public.notify_engagement() from public;
revoke execute on function public.notify_tip() from public;
revoke execute on function public.notify_message() from public;
revoke execute on function public.handle_new_user() from public;
revoke execute on function public.set_updated_at() from public;
revoke execute on function public.record_post_impression(uuid) from public;
grant execute on function public.record_post_impression(uuid) to authenticated;
revoke execute on function public.has_role(uuid, public.app_role) from public;
revoke execute on function public.is_staff() from public;
revoke execute on function public.owns_profile(uuid) from public;
revoke execute on function public.current_profile_id() from public;
revoke execute on function public.is_workspace_member(uuid, uuid) from public;
grant execute on function public.has_role(uuid, public.app_role) to anon, authenticated;
grant execute on function public.is_staff() to anon, authenticated;
grant execute on function public.owns_profile(uuid) to anon, authenticated;
grant execute on function public.current_profile_id() to anon, authenticated;
grant execute on function public.is_workspace_member(uuid, uuid) to anon, authenticated;